replicaCount: 2

storage:
  type: local
  uploadDir: uploads
  outputDir: output
  aws:
    credentials: session
    region: aws-region

image:
  repository: loadinggreg/fiapx-video-processor
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30081

mysql:
  database: springdb
  user: springuser

persistence:
  size: 10Gi
  storageClass: standard

userManagement:
  url: "http://fiapx-user-management-cluster-ip-svc:80"
