apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  {{- if eq .Values.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}